### ISSUE TITLE
Kanban board for js-capstone

### ISSUE THREAD

**Issue by Zven94** [Zven94/JS-group-capstone#21]
Student A: @hajnaloltyan 
Student B: @Zven94 

Project link: [https://github.com/Zven94/JS-group-capstone/projects/1]

**Comment by zainsadaqat** [comment]
# Pull Request Approved ✅ 🎊 🎉 
## Hello @Zven94 and @hajnaloltyan  👋 

### You're good to go working on a group project, Best of Luck! There is nothing else to say other than it's time to merge it.

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 ☑️ 

<img src="https://media1.giphy.com/media/3KC2jD2QcBOSc/giphy.gif"/>

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
